server.port=8081

spring.application.name=account-service

spring.datasource.url=jdbc:h2:mem:accountdb
spring.datasource.driverClassName=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create
sping.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.h2.console.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always